# Generated by Django 5.1 on 2024-10-15 05:27

import django.core.validators
import django.db.models.deletion
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, max_length=300, null=True, upload_to=videos.models.Show.cover_image_upload_path)),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
                ('frame_count', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9000)])),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('in_design', 'In Design'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('archived', 'Archived')], default='unassigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=300, upload_to=videos.models.Video.video_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.show')),
            ],
            options={
                'unique_together': {('show', 'file')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(226)])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='videos.show')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='videos.video')),
            ],
            options={
                'unique_together': {('show', 'location_number')},
            },
        ),
    ]
