# Generated by Django 5.1 on 2024-10-07 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brick',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(226)])),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BrickHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('brick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bricks.brick')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bricks.status')),
            ],
        ),
        migrations.AddField(
            model_name='brick',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='bricks', to='bricks.status'),
        ),
    ]
